# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-cc1101"
BBFILE_PATTERN_meta-cc1101 = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-cc1101 = "6"

LAYERDEPENDS_meta-cc1101 = "core"
LAYERSERIES_COMPAT_meta-cc1101 = "kirkstone"
