#!/bin/sh

case "$1" in
    start)
        /usr/sbin/usb-gadget.sh
        ;;
    stop)
        if [ -e /sys/kernel/config/usb_gadget/radio_gadget/UDC ]; then
            echo "" > /sys/kernel/config/usb_gadget/radio_gadget/UDC
        fi
        ;;
esac

exit 0
